### PR TITLE
Make dashboard timeseries zoom interactive

### PR DESCRIPTION
**Pull request by ncclementi**
- [x] Closes https://github.com/coiled/coiled-runtime/issues/416

I'm only making the time-series plots interactive. I assume we don't need this for the bar charts. Do we?

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ncclementi! 

We're seeing an interesting (I think unrelated) failure 

```python
___________________ ERROR at setup of test_rechunk_in_memory ___________________
[gw8] linux -- Python 3.9.13 /usr/share/miniconda3/envs/test/bin/python

request = <SubRequest 'small_cluster' for <Function test_rechunk_in_memory>>
dask_env_variables = {'DASK_COILED__TOKEN': '***'}

    @pytest.fixture(scope="module")
    def small_cluster(request, dask_env_variables):
        # Extract `backend_options` for cluster from `backend_options` markers
        backend_options = merge(
            m.kwargs for m in request.node.iter_markers(name="backend_options")
        )
        module = os.path.basename(request.fspath).split(".")[0]
>       with Cluster(
            name=f"{module}-{uuid.uuid4().hex[:8]}",
            n_workers=10,
            worker_vm_types=["t3.large"],  # 2CPU, 8GiB
            scheduler_vm_types=["t3.xlarge"],
            backend_options=backend_options,
            package_sync=True,
            environ=dask_env_variables,
        ) as cluster:

conftest.py:412: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/_beta/cluster.py:402: in __init__
    raise e
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/_beta/cluster.py:384: in __init__
    self.sync(self._start)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/cluster.py:514: in sync
    return super().sync(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/utils.py:320: in sync
    return sync(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/utils.py:387: in sync
    raise exc.with_traceback(tb)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/distributed/utils.py:360: in f
    result = yield future
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/tornado/gen.py:762: in run
    value = future.result()
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/context.py:77: in wrapper
    return await func(*args, **kwargs)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/_beta/cluster.py:597: in _start
    env = await magic.create_environment_approximation(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:583: in create_environment_approximation
    conda_env = await conda_env_future
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:234: in approximate
    return await self.iterate_conda_packages()
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:280: in iterate_conda_packages
    packages = await asyncio.gather(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:297: in handle_conda_package
    return await self.create_conda_package_info(name=name, pkg=pkg)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:324: in create_conda_package_info
    if pkg.subdir != "noarch" and not await self.repo_cache.is_available(
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:184: in is_available
    repo_data = await self.fetch_repo_data(channel=channel_url + "/linux-64")
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:173: in fetch_repo_data
    await self.load_channel_repo_data(channel)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/backoff/_async.py:133: in retry
    ret = await target(*args, **kwargs)
/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/coiled/magic.py:152: in load_channel_repo_data
    data = json.loads(channel_fp.read_text())
/usr/share/miniconda3/envs/test/lib/python3.9/json/__init__.py:346: in loads
    return _default_decoder.decode(s)
/usr/share/miniconda3/envs/test/lib/python3.9/json/decoder.py:337: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7f46ac756760>, s = '', idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.
    
        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.
    
        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/usr/share/miniconda3/envs/test/lib/python3.9/json/decoder.py:355: JSONDecodeError
```

This looks `package_sync`-related cc @shughes-uk

**Review by jrbourbeau — COMMENTED** [review]
It looks like I can drag the contents of the plot around / double check the plot to go back to the original configuration. Is there a way I can zoom in a specific section?

**Comment by ian-r-rose** [comment]
> It looks like I can drag the contents of the plot around / double check the plot to go back to the original configuration. Is there a way I can zoom in a specific section?

Scrolling works for me

**Comment by jrbourbeau** [comment]
Me too (weeee)

**Comment by shughes-uk** [comment]
Thanks @jrbourbeau , that's conda's CDN failing to serve repodata.json, fairly easy to fix and i've created an issue for it. cheers

**Pull request merged**
