### PR TITLE
Measure cluster connect time

### PR DESCRIPTION
**Pull request by crusaderky**
- Measure cluster reconnect time. The test already existed but it was not recording anything.
- Remove auto_benchmark_time fixture, as it was sensitive to ordering issues with other fixtures

### CODE REVIEW

**Comment by crusaderky** [comment]
Ready for review and merge

**Comment by ntabris** [comment]
@crusaderky I might be confused. There was some rpc call or something that you suspected was significantly affecting wall-clock on some test runs. I had assumed that was what you wanted to measure here, but maybe that's not the case.

**Comment by crusaderky** [comment]
Client connect time to a cluster is a crude proxy for a new RPC call - although it does quite a bit more stuff on top of that.

**Comment by crusaderky** [comment]
I will merge this at COB today unless there are comments

**Comment by crusaderky** [comment]
@ntabris how would you visualize in the static dashboard the data from all other tests? You would need an entirely ad-hoc series of functions in `dashboard.py` in order to show it.

**Comment by fjetter** [comment]
I think visualization and measurement is not necessarily the same thing. We could measure it for every test but only write it to the DB once. Something like

```python

@pytest.mark.fixture(scope="session")
def measure_connect_time(benchmark_db_engine):

    with Session(benchmark_db_engine, future=True) as session, session.begin() as benchmark_db_session:
        run = TestRun(
            session_id=testrun_uid,
            name="connect-time",
            originalname="connect-time",
            path=str(request.node.path.relative_to(TEST_DIR)),
            dask_version=dask.__version__,
            distributed_version=distributed.__version__,
            coiled_runtime_version=COILED_RUNTIME_VERSION,
            coiled_software_name=COILED_SOFTWARE_NAME,
            python_version=".".join(map(str, sys.version_info)),
            platform=sys.platform,
            ci_run_url=WORKFLOW_URL,
        )
        yield run

        rep = getattr(request.node, "rep_setup", None)
        if rep:
            run.setup_outcome = rep.outcome
        rep = getattr(request.node, "rep_call", None)
        if rep:
            run.call_outcome = rep.outcome
        rep = getattr(request.node, "rep_teardown", None)
        if rep:
            run.teardown_outcome = rep.outcome
        yield run
        benchmark_db_session.add(run)

def small_client(..., measure_connect_time):
    start = time()
    with Client(...):
        measure_connect_time.appropriate_field.update(time() - start)
        ... 
```

The code is not functioning but the idea is to have a global measurement we update. We'll write it to the DB as if it was a test case but we will not have an actual test case.

There are possibly more things we would like to collect globally in which case this kind of approach would pay off. If it's just about the one metric, I don't mind running an extra test.

**Comment by ntabris** [comment]
thanks @fjetter, I think I endorse all of what you said in https://github.com/coiled/coiled-runtime/pull/489#issuecomment-1327699785

**Comment by crusaderky** [comment]
Removed the offending test.
The measure of client connect time can be done in a separate PR.
Ready for review and merge again.

**Comment by crusaderky** [comment]
Merging COB today if there are no objections

**Review by ncclementi — APPROVED** [review]
LGTM

**Pull request merged**
