### PR TITLE
Add button for manually rebuilding software environments

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Alright, manually rebuilding software environments

**Comment by marcosmoyano** [comment]
@jrbourbeau  I just changed the oss-benchmark-bot account in staging to fix the errors. Can we give this another try?

**Comment by jrbourbeau** [comment]
Awesome, thanks @marcosmoyano! Coiled software envs on staging were never updated, so it's okay that those builds are failing here because this PR is just about reverting some recent updates. However, those account permission updates will be useful over in https://github.com/coiled/coiled-runtime/pull/154

**Comment by jrbourbeau** [comment]
> Did the test not run?

That's correct, looking at the latest CI run for that PR https://github.com/coiled/coiled-runtime/pull/154/commits/af8513375a2aa2d66adfeb4d43acf1d3453f62fd test did not run. If they were to have run I suspect they would have failed for the same reasons as what we were seeing on `main` (xref https://github.com/coiled/coiled-runtime/issues/163)

**Comment by ncclementi** [comment]
> > Did the test not run?
> 
> That's correct, looking at the latest CI run for that PR [af85133](https://github.com/coiled/coiled-runtime/commit/af8513375a2aa2d66adfeb4d43acf1d3453f62fd) test did not run. If they were to have run I suspect they would have failed for the same reasons as what we were seeing on `main` (xref #163)

Oh, I thought you were trying this separately. In my PR things didn't run because I commented them out until I knew the action worked. You can see at the bottom of the diff that things are commented on purpose

**Comment by jrbourbeau** [comment]
We tried it separately in an earlier commit in this PR https://github.com/coiled/coiled-runtime/pull/162/commits/25d98128b95d6b8019f0772588d6ea5a7940fd03. If you look at the CI for that run, you'll see failures like 

```python
coiled.errors.ClusterCreationError: Cluster status is error (reason: Scheduler Stopped -> Process never phoned home) (cluster_id: 32482)
```

**Pull request merged**
