### PR TITLE
Revert "OLS Workload" fix ci debugging code. 

### PR DESCRIPTION
**Pull request by ncclementi**
Reverts only changes in `test.yml` introduced in coiled/coiled-runtime#443

### CODE REVIEW

**Comment by ncclementi** [comment]
It looks like we have a legit failure in windows https://github.com/coiled/coiled-runtime/actions/runs/3576035693/jobs/6013493204#step:5:269

**Comment by ncclementi** [comment]
@gjoseph92 Do you know if this error is expected on windows? I'm not super familiar with the `scaled_array_shape` utility, but if this is expected to fail on windows?

**Comment by gjoseph92** [comment]
It should not fail on windows and there's no reason why windows would be related to the failure

**Comment by ncclementi** [comment]
> It should not fail on windows and there's no reason why windows would be related to the failure

Well I'm not sure what's the reason for the failure, it looks like the nbytes are not calculated properly. I do not have a way to investigate this without a windows machine, nor the time. I think I will skip the test on windows for now and open an issue about it.

**Comment by gjoseph92** [comment]
> I think I will skip the test on windows for now and open an issue about it

Sure, but I don't see a reason why windows would be related to it. Unless it reproduces on windows I'm not sure why we'd skip it?

**Comment by ntabris** [comment]
haven't looked closely so maybe this is unhelpful but should `actual_nbytes` ever be negative, or is the fact that it is mean there's likely overflow or something like that?

**Comment by ncclementi** [comment]
> Sure, but I don't see a reason why windows would be related to it. Unless it reproduces on windows I'm not sure why we'd skip it?

It reproduces on windows at least on ci, I ran it 4 times, always failed on windows.

**Comment by gjoseph92** [comment]
That's bizarre, thanks for re-running it and confirming. I guess it is some sort of overflow issue on windows? Maybe in the `np.prod`?

**Pull request merged**
