### PR TITLE
Fix GHA set-output deprecation

### LINKED ISSUE #604: GH Actions deprecation of set-output
GH actions is warning us that the set-output command is deprecated and will be disabled soon. We should migrate according to the docs

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

```

### PR DESCRIPTION
**Pull request by ncclementi**
- Closes #604

Modify set-output usage according to suggestions here https://github.com/orgs/community/discussions/35994

### CODE REVIEW

**Review by fjetter — APPROVED** [review]
Did you test this once?

**Comment by ncclementi** [comment]
No, I did not because CI was completely broken on Friday due to the package sync issue. 
I can trigger the A/B workflow now if CI is ok, haven't had a chance to take a look

**Comment by ncclementi** [comment]
@crusaderky and @fjetter the change works as the discoveries are happening, see test example here https://github.com/coiled/coiled-runtime/actions/runs/3677799131/jobs/6220268388

I ran only the runtime folder as it's the smallest one and they are not passing due to the packaging problem, but the change to use `GITHUB_OUTPUT` seems to be working.

**Comment by ncclementi** [comment]
Everything looks green!. 
Re-run CI by merging main with the packaging fixes, and checked that AB testing works with the changes here see https://github.com/coiled/coiled-runtime/actions/runs/3678760100 more specifically https://github.com/coiled/coiled-runtime/actions/runs/3678760100/jobs/6222405290#step:5:10

I will merge this!

**Pull request merged**
