### PR TITLE
Overlap sample

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @phobson @ian-r-rose for review

**Review by jrbourbeau — COMMENTED** [review]
Thanks @mrocklin. This is consistently giving a 

```python
distributed.scheduler.KilledWorker: ("('block-info-_trim-ed1ddf42924b14064b622735c39d321a', 100, 100)", <WorkerState 'tls://10.0.11.157:44589', name: test_array-f43e3d4b-worker-3f97c8be71, status: closed, memory: 0, processing: 1>)
```

Need to look into why more...

**Comment by jrbourbeau** [comment]
```python
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]: 2022-09-29 19:43:11,539 - distributed.core - ERROR - keywords must be strings
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]: Traceback (most recent call last):
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/core.py", line 667, in handle_stream
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     handler(**merge(extra, msg))
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/worker.py", line 1930, in _
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     event = cls(**kwargs)
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "<string>", line 13, in __init__
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/worker_state_machine.py", line 627, in __post_init__
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     self.run_spec = SerializedTask(**self.run_spec)
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]: TypeError: keywords must be strings
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]: 2022-09-29 19:43:11,545 - distributed.worker - ERROR - keywords must be strings
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]: Traceback (most recent call last):
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/worker.py", line 197, in wrapper
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     return await method(self, *args, **kwargs)
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/worker.py", line 1280, in handle_scheduler
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     await self.handle_stream(comm)
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/core.py", line 667, in handle_stream
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     handler(**merge(extra, msg))
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/worker.py", line 1930, in _
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     event = cls(**kwargs)
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "<string>", line 13, in __init__
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:   File "/opt/conda/lib/python3.9/site-packages/distributed/worker_state_machine.py", line 627, in __post_init__
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]:     self.run_spec = SerializedTask(**self.run_spec)
Sep 29 19:43:11 ip-10-0-11-157 cloud-init[870]: TypeError: keywords must be strings
```

**Comment by jrbourbeau** [comment]
This is a known issue with `map_overlap` that has been resolved in more recent `dask` releases (xref https://github.com/coiled/coiled-runtime/issues/306)

**Review by jrbourbeau — APPROVED** [review]

**Pull request merged**
