### PR TITLE
Test upcoming Dask 2022.05.2 release

### PR DESCRIPTION
**Pull request by jrbourbeau**
There's a planned `dask` and `distributed` release for later today (xref https://github.com/dask/community/issues/250). Let's run CI here against the `main` branch of `dask` / `distributed` to make sure things pass (I expect they will)

### CODE REVIEW

**Comment by jrbourbeau** [comment]
I'm seeing

```python
E           coiled.errors.ServerError: Internal error occured, contact customer service and quote 35214e0e-02a3-4de4-958e-2597ce96b405
```

in one of the CI builds. cc @dchudz @ntabris @shughes-uk in case you have thoughts

**Comment by ntabris** [comment]
> Internal error occured, contact customer service and quote 35214e0e-02a3-4de4-958e-2597ce96b405

Oddly I can't find this id in our logs. Can you try re-running the CI job and see if it works this time?

**Comment by jrbourbeau** [comment]
So all the upstream builds are hanging due to https://github.com/dask/distributed/issues/6437. I'll cancel for now and then re-run once https://github.com/dask/distributed/pull/6458 is merged. That PR should fix this issue and also be included in the upcoming release

**Comment by jrbourbeau** [comment]
Okay, so more almost all tests are passing. It looks like one cluster randomly had an issue and failed at `client.wait_for_workers(10)`, which is known to have issues

**Pull request closed without merging**
