### PR TITLE
Repeat A/B tests

### PR DESCRIPTION
**Pull request by crusaderky**

### CODE REVIEW

**Comment by crusaderky** [comment]
@fjetter @ian-r-rose @hendrikmakait @gjoseph92 @jrbourbeau @ncclementi 

This is ready for review.
However, it heavily conflicts with #235, which has been just merged. I'll need an extra day (at least) to re-engineer it.

**Comment by crusaderky** [comment]
A/B tests evidence: https://github.com/coiled/coiled-runtime/suites/8311157631/artifacts/364978026

**Comment by fjetter** [comment]
> However, it heavily conflicts with https://github.com/coiled/coiled-runtime/pull/235, which has been just merged. I'll need an extra day (at least) to re-engineer it.

I believe these changes offer enough value to invest another day or two. We knew that there will be some migration effort before we started.

**Comment by crusaderky** [comment]
Superseded by #355

**Pull request closed without merging**
