### PR TITLE
Try removing explicit region to see what breaks.

### PR DESCRIPTION
**Pull request by ian-r-rose**

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Everything seems in order, I couldn't find any problems with removing the region

**Comment by ian-r-rose** [comment]
Failure to build a software environment -- haven't seen one of those in a while, but wouldn't happen with in a `package_sync` world (we'd have fun new errors).

**Review by ncclementi — APPROVED** [review]

**Comment by ncclementi** [comment]
> Failure to build a software environment -- haven't seen one of those in a while, but wouldn't happen with a `package_sync` world (we'd have fun new errors).

I'm not sure I follow this, I bet this was supposed to go on a different PR CI?

**Comment by ian-r-rose** [comment]
> I'm not sure I follow this, I bet this was supposed to go on a different PR CI?

There was a previous failure, I re-ran it.

**Pull request merged**
